Public Class AccountGroupsClass
    Public BankAccounts As String = "Bank Accounts"
    Public BankOD As String = "Bank O D"
    Public CapitalAccounts As String = "Capital Accounts"
    Public CashAccounts As String = "Cash Accounts"
    Public CurrentAssets As String = "Current Assets"
    Public CurrentLiabilities As String = "Current Liabilities"
    Public CustomersAccounts As String = "Customers Accounts"
    Public DepositsAccountsAssets As String = "Deposits Accounts (Assets)"
    Public DirectExpenses As String = "Direct Expenses"
    Public DirectIncomes As String = "Direct Incomes"
    Public DutiesTaxes As String = "Duties & Taxes"
    Public FixedAssets As String = "Fixed Assets"
    Public IndirectExpenses As String = "Indirect Expenses"
    Public IndirectIncomes As String = "Indirect Incomes"
    Public LoansAdvancesAssets As String = "Loans & Advances (Assets)"
    Public LoansAccountsLaibilities As String = "Loans Accounts (Laibilities)"
    Public ProfitLossAccounts As String = "Profit & Loss Accounts"
    Public ProvisionsAcounts As String = "Provisions Acounts"
    Public PurchaseAccounts As String = "Purchase Accounts"
    Public SalesAccounts As String = "Sales Accounts"
    Public StockAccounts As String = "Stock Accounts"
    Public SuppliersAccounts As String = "Suppliers Accounts"
    Public SuspenseAccounts As String = "Suspense Accounts"
    
End Class
