Public Class PrintVoucherNamesClass

    Public purchasegoods As String = "purchase goods"
    Public purchasequote As String = "purchase Quote"
    Public purchaseorder As String = "purchase order"
    Public purchaseinvoice As String = "purchase invoice"
    Public purchasereturns As String = "purchase returns"
    Public salespos As String = "sales pos"
    Public salesquote As String = "sales quote"
    Public salesorder As String = "sales order"
    Public salesdelivery As String = "sales delivery"
    Public salesinvoice As String = "sales invoice"
    Public salesreturns As String = "sales returns"
    Public payment As String = "payment"
    Public receipt As String = "receipt"
    Public journal As String = "journal"
    Public contra As String = "contra"
    Public purchasevoucher As String = "purchase voucher"
    Public debitnote As String = "debit note"
    Public salesvoucher As String = "sales voucher"
    Public creditnote As String = "credit note"
    Public other1 As String = "other1"
    Public other2 As String = "other2"
    Public other3 As String = "other3"
    Public other4 As String = "other4"
    Public other5 As String = "other5"

    Public Form8 As String = "Form8"
    Public Form8b As String = "Form8B"
    Public form8D As String = "Form8D"
    Public SRForm8 As String = "SRForm8"
    Public SRForm8b As String = "SRForm8B"
    Public SRform8D As String = "SRForm8D"
    Public cashsales As String = "cashsales"
    Public creditsales As String = "creditsales"
    Public cashpurchase As String = "cashpurchase"
    Public creditpurchase As String = "creditpurchase"

    Public purchasegoodsDetailes As String = "PurchgoodsDetails"
    Public purchaseorderDetailes As String = "PurchorderDetails"
    Public purchaseinvoiceDetailes As String = "PurchinvoiceDetails"
    Public purchasereturnsDetailes As String = "PurchinvoiceRetDetails"
    Public purchaseQutoDetailes As String = "PurchQutoDetails"

    Public purchasegoodsItemRows As String = "PurchgoodsRowItems"
    Public purchaseorderItemRows As String = "PurchorderRowItems"
    Public purchaseinvoiceItemRows As String = "PurchinvoiceRowItems"
    Public purchasereturnsItemRows As String = "PurchinvoiceRetRowItems"
    Public purchaseQutoItemRows As String = "PurchQutoRowItems"

    Public salesposDetailes As String = "SalesPosDetails"
    Public salesquoteDetailes As String = "SalesQutoDetails"
    Public salesorderDetailes As String = "SalesOrderDetails"
    Public salesdeliveryDetailes As String = "SalesDelaveryDetails"
    Public salesinvoiceDetailes As String = "SalesInvoiceDetails"
    Public salesreturnsDetailes As String = "SalesreteDetails"

   
    Public salesposItemRows As String = "SalesPosRowItems"
    Public salesquoteItemRows As String = "SalesQutoRowItems"
    Public salesorderItemRows As String = "SalesOrderRowItems"
    Public salesdeliveryItemRows As String = "SalesDelaveryRowItems"
    Public salesinvoiceItemRows As String = "SalesInvoiceRowItems"
    Public salesreturnsItemRows As String = "SalesreteRowItems"


End Class
